config/routes.rb
Rails.application.routes.draw do
  resources :repositories, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'new'  => 'repositories#new', :as=>:new_repository
  get '/:technology' => 'browsers#category', :as=>:browser_technology
  get '/:technology/:category' => 'browsers#hierarchy', :as=>:browser_hierarchy
  get '/:technology/:category/:owner/:name' => 'browsers#repository', :as=>:browser_repository
  root 'browsers#technology'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :hierarchies
end

app/models/hierarchy.rb
class Hierarchy < ApplicationRecord
    has_many :repositories
end

app/models/repository.rb
class Repository < ApplicationRecord
    validates :name, presence: true
    validates :owner, presence: true
end

app/models/technology.rb
class Technology < ApplicationRecord
    validates :name, presence: true
    has_many :hierarchies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  class QueryError < StandardError; end
  
  def query(definition, variables = {})
      response = Cuong::Client.query(definition, variables: variables, context: client_context)

      if response.errors.any?
        raise QueryError.new(response.errors[:data].join(", "))
      else
        response.data
      end
    end
    
    def client_context
      # Use static access token from environment. However, here we have access
      # to the current request so we could configure the token to be retrieved
      # from a session cookie.
      { access_token: Cuong::Application.secrets.github_access_token }
    end
end

app/controllers/browsers_controller.rb
class BrowsersController < ApplicationController
    def technology
        @technologies = Technology.all
    end
    
    def category
        @technology = Technology.find_by_name(params[:technology])
        @hierarchies = Hierarchy.where(:technology_id => @technology.id)
        @categories = Category.where(:id => @hierarchies.map {|hierarchy| hierarchy.id})
    end
    
    def hierarchy
        @technology = Technology.find_by_name(params[:technology])
        @category = Category.find_by_name(params[:category])
        @hierarchy = Hierarchy.find_by(technology_id: @technology.id, category_id: @category.id)
        @repositories = Repository.where(:hierarchy_id => @hierarchy.id)
    end
    
    def repository
        @technology = Technology.find_by_name(params[:technology])
        @category = Category.find_by_name(params[:category])
        @hierarchy = Hierarchy.find_by(technology_id: @technology.id, category_id: @category.id)
        @repository = Repository.find_by(hierarchy_id: @hierarchy.id, owner: params[:owner], name: params[:name])
    end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[ show edit update destroy ]
  
  Graphql = Cuong::Client.parse <<-'GRAPHQL'
    query($owner: String!, $name: String!)  { 
      repository(owner: $owner, name: $name) {
        stargazerCount,
        forkCount,
        defaultBranchRef{
            target{
                ... on Commit{
                    history(first:1){
                        edges{
                            node{
                                ... on Commit{
                                    committedDate
                                }
                            }
                        }
                    }
                }
            }
        }
      }
    }
  GRAPHQL

  
  def new
  end

  def create
    @repo_owner = params[:repository][:repository].split("/")[0]
    @repo_name = params[:repository][:repository].split("/")[1]
    
    data = query Graphql, owner: @repo_owner, name: @repo_name
    
    if not data.repository
      respond_to do |format|
        format.html { redirect_to new_repository_path, notice: "Createion failed. Failed to query github repo data"}
      end
      return
    end
    
    @technology = Technology.find_or_create_by(name: params[:repository][:technology])
    @category = Category.find_or_create_by(name: params[:repository][:category])
    @hierarchy = Hierarchy.find_or_create_by(technology_id: @technology.id, category_id: @category.id)
    @repository = @hierarchy.repositories.build(
      name: @repo_name,
      owner: @repo_owner,
      stargazer_count: data.repository.stargazerCount,
      fork_count: data.repository.forkCount,
      since_last_commit: (Time.now - Time.parse(data.repository.defaultBranchRef.target.history.edges.first.node.committedDate))/(24*60*60),
    )

    respond_to do |format|
      if @repository.save
        format.html { redirect_to browser_repository_path(@technology.name, @category.name, @repo_owner, @repo_name), notice: "Github repo was successfully created." }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repository_params
      params.require(:repository).permit(:name, :owner, :hierarchy_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browsers_helper.rb
module BrowsersHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/browsers/category.html.erb
<p id="notice"><%= notice %></p>

<h1>Hierarchies</h1>
<h2>Technology: <%= @technology.name %></h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, browser_hierarchy_path(@technology.name, category.name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path%>

app/views/browsers/hierarchy.html.erb
<p id="notice"><%= notice %></p>

<h1>Repositories</h1>

<h2>Technology: <%= @technology.name %></h2>
<h2>Category: <%= @category.name %></h2>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Name</th>
       <th>Star Count</th>
       <th>Fork Count</th>
       <th>Days Since Last Commit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.owner %></td>
        <td><%= link_to repository.name, browser_repository_path(@technology.name, @category.name, repository.owner, repository.name) %></td>
        <td><%= repository.stargazer_count %></td>
        <td><%= repository.fork_count %></td>
        <td><%= repository.since_last_commit %> days</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', browser_technology_path(@technology.name) %>

app/views/browsers/repository.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Technology:</strong>
  <%= @technology.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @repository.owner %>
</p>

<p>
  <strong>Hierarchy:</strong>
  <%= @repository.hierarchy_id %>
</p>

<p>
  <strong>Star Count:</strong>
  <%= @repository.stargazer_count %>
</p>

<p>
  <strong>Folk Count:</strong>
  <%= @repository.fork_count %>
</p>

<p>
  <strong>Day since last commit:</strong>
  <%= @repository.since_last_commit %>
</p>

<%= link_to 'Back', browser_hierarchy_path(@technology.name, @category.name) %>

app/views/browsers/technology.html.erb
<p id="notice"><%= notice %></p>

<h1>Technologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= link_to technology.name, browser_technology_path(technology.name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Repository', new_repository_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cuong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/_form.html.erb
<%= form_for(repository) do |f| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </div>

  <div class="field">
    <%= f.label :hierarchy_id %>
    <%= f.number_field :hierarchy_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repositories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Hierarchy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.name %></td>
        <td><%= repository.owner %></td>
        <td><%= repository.hierarchy_id %></td>
        <td><%= link_to 'Show', repository %></td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Repository</h1>

<%= form_for(:repository, url: repositories_path) do |f| %>
      <%= f.label :technology %>
      <%= f.text_field :technology %>
      
      <%= f.label :category %>
      <%= f.text_field :category %>
      
      <%= f.label :repository %>
      <%= f.text_field :repository %>

      <%= f.submit "Create repo", class: "btn btn-primary" %>
    <% end %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @repository.owner %>
</p>

<p>
  <strong>Hierarchy:</strong>
  <%= @repository.hierarchy_id %>
</p>

<p>
  <strong>Star Count:</strong>
  <%= @repository.stargazer_count %>
</p>

<p>
  <strong>Folk Count:</strong>
  <%= @repository.folk_count %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>